### ISSUE TITLE
Didn't work properly in Speaker Mode

### ISSUE THREAD

**Issue by libralibra** [Martinomagnifico/quarto-appearance#3]
The animated items won't show in speaker mode.

**Comment by Martinomagnifico** [comment]
I’ll check it out this weekend

**Comment by libralibra** [comment]
> I’ll check it out this weekend

Thanks @Martinomagnifico ! 

BTW: Actually, I'm quite new to CSS, HTML, and JavaScript. I am curious about how to modify the reveal js functions. I tried to modify the file in js folder and include it in HTML but it didn't work. And I don't know how to debug with the js in 'dist' folder. Cannot find anywhere showing how to modify the js files.

**Comment by Martinomagnifico** [comment]
This was fixed in version 1.2.1
