### ISSUE TITLE
Some fragments are missing if 'data-auto-animate' was set for section

### ISSUE THREAD

**Issue by libralibra** [Martinomagnifico/quarto-appearance#4]
If multiple sections with 'data-auto-animate' which should animate between them without the global slide transition effect, some fragments are missing (not showing at all) by progressing using <kbd>SPACE</kbd>, <kbd>&darr;</kbd>, or <kbd>&rarr;</kbd>.

Any thoughts on this?

**Comment by Martinomagnifico** [comment]
Could you email me an example? That makes it easier to troubleshoot.

**Comment by libralibra** [comment]
> Could you email me an example? That makes it easier to troubleshoot.

Hi, I just found this bug by accident. Any dummy slides would show the bug clearly. Please copy the following 2 slides to your slide deck and try to navigate between them. The second slide content won't appear for some reason.

```
<section data-auto-animate>
    <h1>Test Slide 1</h1>
    <ul>
        <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. </li>
        <li>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </li>
        <li>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </li>
        <li>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</li>
    </ul>
</section>

<section data-auto-animate>
    <h1>Test Slide 2</h1>
    <ul>
        <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. </li>
        <li>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </li>
        <li>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </li>
        <li>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</li>
    </ul>
</section>
```

The sessions for your plug in is:


```
autoelements: {
      "ul li": { "animation": "animate__flipInX", "speed": "faster", "delay": "50" },
      'ol li': {
          "animation": 'animate__jackInTheBox', 'speed': "faster", 'delay': '50'
      },
  },
```


Please refer to the attached screencast. The two slides (test slide 1 and 2) should have the same content (ul>li). But some of them (not always the same one) won't appear between navigations.
![autoelement_bug](https://github.com/Martinomagnifico/quarto-appearance/assets/875627/9c92fcb3-1409-49e0-bd09-996d9111a039)

**Comment by Martinomagnifico** [comment]
Whenever there's an animation attached to an element in a `data-auto-animate slide`, Reveal adds some CSS to it, in an inline stylesheet with references to the element. That makes it hard to fix. Now when you have an element, like above, which is the same across the slides, you will only want to animate them on the first slide.

Try to add the following to your HTML, **_after_** the Appearance CSS. If it works for you (or anyone else), it will be added to the plugin. Animation will only happen once in this case, there's nothing we can do about it. This is because in slides without Appearance, you can go back and forth between the slides and elements can then transition. However, Appearance uses animations, not transitions, and mixing them will not work correctly.  

```
<style>
.animate__animated[data-auto-animate-target]:not([data-auto-animate-target=unmatched]) {
    animation: none;
}
[data-auto-animate=running] .animate__animated[data-auto-animate-target]:not([data-auto-animate-target=unmatched]) {
    opacity: 1 !important;
}
</style> 
```

Play around with it to see if it fits your needs. Anyone else can try it out and leave comments here as well. 
If you do want an animation on a (same) element on a next slide, just nest it inside a div.

**Comment by libralibra** [comment]
> <section data-auto-animate>
>     <h1>Test Slide 1</h1>
>     <ul>
>         <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. </li>
>         <li>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </li>
>         <li>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </li>
>         <li>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</li>
>     </ul>
> </section>
> 
> <section data-auto-animate>
>     <h1>Test Slide 2</h1>
>     <ul>
>         <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. </li>
>         <li>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </li>
>         <li>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </li>
>         <li>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</li>
>     </ul>
> </section>

really nice fix! although I don't quite understand how you did it!

But it works! :-)

**Comment by libralibra** [comment]
> Whenever there's an animation attached to an element in a `data-auto-animate slide`, Reveal adds some CSS to it, in an inline stylesheet with references to the element. That makes it hard to fix. Now when you have an element, like above, which is the same across the slides, you will only want to animate them on the first slide.
> 
> Try to add the following to your HTML, **_after_** the Appearance CSS. If it works for you (or anyone else), it will be added to the plugin. Animation will only happen once in this case, there's nothing we can do about it. This is because in slides without Appearance, you can go back and forth between the slides and elements can then transition. However, Appearance uses animations, not transitions, and mixing them will not work correctly.
> 
> ```
> <style>
> .animate__animated[data-auto-animate-target]:not([data-auto-animate-target=unmatched]) {
>     animation: none;
> }
> [data-auto-animate=running] .animate__animated[data-auto-animate-target]:not([data-auto-animate-target=unmatched]) {
>     opacity: 1 !important;
> }
> </style> 
> ```
> 
> Play around with it to see if it fits your needs. Anyone else can try it out and leave comments here as well. If you do want an animation on a (same) element on a next slide, just nest it inside a div.

really nice fix! although I don't quite understand how you did it!

But it works! :-)

**Comment by libralibra** [comment]
ah, I don't know why I came and posted here under quarto-version, but I am actually using the original reveal.js framework.
You fixed worked for both I assume. Awsome!
