### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by benubah** [Martinomagnifico/quarto-appearance#5]
Hi,

This theme looks lovely...thanks for providing it

Is there a way to add a navigation bar or table of contents so that the user sees where they're at as they move through the presentation?

**Comment by Martinomagnifico** [comment]
That would be an other of my plugins: https://github.com/Martinomagnifico/quarto-simplemenu

**Comment by benubah** [comment]
> That would be an other of my plugins: https://github.com/Martinomagnifico/quarto-simplemenu

Wow! Thanks! How can I get the navigation arrows to show at the bottom-right just like in the Appearance template?

**Comment by Martinomagnifico** [comment]
That’s just a setting in demo.qmd: `controls-layout: bottom-right`. See this file: https://github.com/martinomagnifico/quarto-appearance/blob/main/demo.qmd

**Comment by benubah** [comment]
Yes, it is there in the quarto-simplemenu code: https://github.com/Martinomagnifico/quarto-simplemenu/blob/main/demo.qmd#L12 , but it does not appear in the when we render as seen here: https://martinomagnifico.github.io/quarto-simplemenu/docs/demo.html#/slide-1

![image](https://github.com/Martinomagnifico/quarto-appearance/assets/11357251/0d7240f0-5e1b-4c09-ab01-7d825a1a8e38)

**Comment by benubah** [comment]
Alright, I see that for quarto-simplemenu, I need to set `controls: true` before `controls-layout: bottom-right` can work.

**Comment by Martinomagnifico** [comment]
Ah good catch, I’ll add it to the demo as well. Will close the issue. Thanks!
