### ISSUE TITLE
Incompatibility with letterbox template

### ISSUE THREAD

**Issue by Nenuial** [Martinomagnifico/quarto-appearance#6]
Hi,
First of all, let me say that I find this extension really useful! Thanks for making it.

I recently tried to combine @EmilHvitfeldt's excellent [letterbox template](https://github.com/EmilHvitfeldt/quarto-revealjs-letterbox) with your appearance plugin. Unfortunately, there seems to be some kind of issue.

I was wondering if you were willing to take a look at it. I made a reprex here : https://github.com/Nenuial/AnimateLetterbox

I suspect the letterbox JavaScript in https://github.com/EmilHvitfeldt/quarto-revealjs-letterbox/blob/main/_extensions/letterbox/theme.html and the JavaScript of appearance don't work well together, but I was unable to find what exactly the problem is.

If you don't want to spend time helping me, I would understand perfectly. The plugin works fine with the base revealjs format!

**Comment by EmilHvitfeldt** [comment]
Hello! I'm out of office for a few more days.

Without having looked at the specifics, it is likely to be a letterbox issue. As I needed to do a lot to make it all work

**Comment by Nenuial** [comment]
Thanks for your message. I have looked at the issue some more, and I found that I was missing some key option for my slides: `transition`! Without a transition set for the slides, the events don't seem to "fire".

I still had some issue with the tweaked version of `theme.html` I'm using to lift logo, footer and the like back into the slides (not available in my reprex). I had do some changes but I think I found a solution that works for now.

**Comment by Martinomagnifico** [comment]
Thanks and good find! Appearance indeed looks for transitions. I’ll see if I can factor in a non-transition deck as well.

**Comment by Martinomagnifico** [comment]
If you put
```
appearance:
  appearevent: 'slidechanged'
```
in the YAML in the beginning of the file, it will work. Somehow the 'hideagain' option does not work in this setup, but at least you'll get the animations.

**Comment by Nenuial** [comment]
Thanks for this. I use the fade transition for now, and everything works now fine!
